server:
  port: 8888
spring:
  application:
    name: remote-config-server
  cloud:
    config:
      server:
        git:
          uri: https://xxxx.git # 远程仓库地址
          search-paths: xxx # 仓库下的路径
      label: master
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/ # 注册中心地址
  instance:
    # 是否将当前服务的ip注册到注册中心，如果只是配置了eureka.instance.prefer-ip-address=true，
    # 不配置 eureka.instance.instance-id 那还是显示 hostname，但 IP地址是可以访问的
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
    #    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}