package com.demo.dao;

import com.demo.model.MybatisTest;
import com.demo.model.MybatisTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MybatisTestDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_test
     *
     * @mbg.generated
     */
    long countByExample(MybatisTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_test
     *
     * @mbg.generated
     */
    int deleteByExample(MybatisTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_test
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_test
     *
     * @mbg.generated
     */
    int insert(MybatisTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_test
     *
     * @mbg.generated
     */
    int insertSelective(MybatisTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_test
     *
     * @mbg.generated
     */
    List<MybatisTest> selectByExample(MybatisTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_test
     *
     * @mbg.generated
     */
    MybatisTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_test
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MybatisTest record, @Param("example") MybatisTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_test
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MybatisTest record, @Param("example") MybatisTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MybatisTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MybatisTest record);
}