package com.demo.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table mybatis_test
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MybatisTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_test.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_test.key
     *
     * @mbg.generated
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_test.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_test.id
     *
     * @return the value of mybatis_test.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_test.id
     *
     * @param id the value for mybatis_test.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_test.key
     *
     * @return the value of mybatis_test.key
     *
     * @mbg.generated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_test.key
     *
     * @param key the value for mybatis_test.key
     *
     * @mbg.generated
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_test.value
     *
     * @return the value of mybatis_test.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_test.value
     *
     * @param value the value for mybatis_test.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value;
    }
}